export const SET_USER = "SET_USER";
export const SET_IS_SIGNING_UP = "SET_IS_SIGNING_UP";
export const SET_IS_LOGGING_IN = "SET_IS_LOGGING_IN";
export const SET_IS_LOGGING_OUT = "SET_IS_LOGGING_OUT";
export const SET_IS_CHECKING_AUTH = "SET_IS_CHECKING_AUTH";
export const SET_CONTENT_TYPE = "SET_CONTENT_TYPE"
export const SET_TRENDING_CONTENT = "SET_TRENDING_CONTENT";